#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract a per-site Astro config file from build.py.

Output: src/sites/<domain>.ts

Usage:
    python3 scripts/extract-config.py <domain>
    python3 scripts/extract-config.py --all
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NETWORK = ROOT.parent / "hvac-network" / "sites"

PILOTS_DONE = {
    "londonheatingcooling.ca",
    "londonhvacpros.ca",
    "londonacrepair.ca",
}
EXCLUDE = {
    "cambridgehvacpros.ca",   # 20 uncommitted local mods (user flagged)
    "dunnvilleheatingcooling.ca",  # hand-built, no WP source
}


def parse_build_py(path: Path) -> dict:
    src = path.read_text(encoding="utf-8")
    f: dict = {}
    for line in src.splitlines():
        s = line.strip()
        for var in ["SITE_NAME", "SHORT_NAME", "DOMAIN", "CITY", "REGION", "REGION_ABBR",
                    "COUNTY", "PHONE_DISPLAY", "PHONE_TEL", "EMAIL",
                    "ADDR_STREET", "ADDR_LOCALITY", "ADDR_REGION", "ADDR_POSTAL"]:
            m = re.match(rf'^{var}\s*=\s*"([^"]+)"', s)
            if m:
                f[var] = m.group(1)
        m = re.match(r'^SERVICE_AREAS\s*=\s*\[([^\]]+)\]', s)
        if m:
            f["SERVICE_AREAS"] = [t.strip().strip("'\"") for t in m.group(1).split(",") if t.strip()]
    # Palette from LOGO_MARK gradient stops + theme-color meta.
    stops = re.findall(r'stop-color="([^"]+)"', src)
    if len(stops) >= 2:
        f["ACCENT"] = stops[0]
        f["ACCENT2"] = stops[1]
    m = re.search(r'name="theme-color" content="#?([0-9a-fA-F]{3,6})"', src)
    if m:
        hex_v = m.group(1)
        if not hex_v.startswith("#"):
            hex_v = "#" + hex_v
        f["THEME_COLOR"] = hex_v
    # OG_IMAGE
    m = re.search(r'^OG_IMAGE\s*=\s*"([^"]+)"', src, re.MULTILINE)
    if m:
        f["OG_IMAGE"] = m.group(1)
    return f


def to_ts_string(s: str) -> str:
    """Emit a TS string literal. Source brand strings use raw &; we keep raw
    for `brand` and emit HTML-escaped `brandHtml` for use in JSX text contexts."""
    return json.dumps(s, ensure_ascii=False)


def emit_config(domain: str, f: dict) -> str:
    brand = f.get("SITE_NAME", domain)
    # brandHtml: HTML-escape any & -> &amp; for use in body prose.
    brand_html = brand.replace("&", "&amp;")
    url = f.get("DOMAIN", f"https://{domain}")
    service_areas = f.get("SERVICE_AREAS", [])
    accent = f.get("ACCENT", "#0369a1")
    accent2 = f.get("ACCENT2", accent)
    theme = f.get("THEME_COLOR", "#0f2544")
    og = f.get("OG_IMAGE", f"{url}/assets/img/og-default.png")

    lines = [
        f"// Per-site config for {domain}",
        f"// AUTO-GENERATED by scripts/extract-config.py from build.py.",
        f"// Brand: \"{brand}\"",
        "import type { SiteConfig } from '../lib/types';",
        "",
        "export const site: SiteConfig = {",
        f"  domain: {to_ts_string(domain)},",
        f"  url: {to_ts_string(url)},",
        f"  brand: {to_ts_string(brand)},",
        f"  brandHtml: {to_ts_string(brand_html)},",
        f"  city: {to_ts_string(f.get('CITY', ''))},",
        f"  region: {to_ts_string(f.get('REGION', 'Ontario'))},",
        f"  regionAbbr: {to_ts_string(f.get('REGION_ABBR', 'ON'))},",
        f"  county: {to_ts_string(f.get('COUNTY', ''))},",
        f"  phone: {{ display: {to_ts_string(f.get('PHONE_DISPLAY', ''))}, tel: {to_ts_string(f.get('PHONE_TEL', ''))} }},",
        f"  email: {to_ts_string(f.get('EMAIL', ''))},",
        "  address: {",
        f"    street: {to_ts_string(f.get('ADDR_STREET', ''))},",
        f"    locality: {to_ts_string(f.get('ADDR_LOCALITY', f.get('CITY', '')))},",
        f"    region: {to_ts_string(f.get('ADDR_REGION', 'ON'))},",
        f"    postal: {to_ts_string(f.get('ADDR_POSTAL', ''))},",
        "  },",
        f"  serviceAreas: {json.dumps(service_areas, ensure_ascii=False)},",
        "  palette: {",
        f"    navy: {to_ts_string(theme)},  // theme-color (dark surface)",
        f"    accent: {to_ts_string(accent)},",
        f"    accent2: {to_ts_string(accent2)},",
        f"    themeColor: {to_ts_string(theme)},",
        "  },",
        f"  ogImage: {to_ts_string(og)},",
        "  tracking: {",
        "    webhookUrl: 'https://auto.sdagents.ai/webhook/hvac-sites',",
        "  },",
        "};",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: extract-config.py <domain> | --all")
        sys.exit(1)
    arg = sys.argv[1]
    if arg == "--all":
        domains = sorted(d.name for d in NETWORK.iterdir()
                         if d.is_dir() and (d / "build.py").exists()
                         and d.name not in PILOTS_DONE
                         and d.name not in EXCLUDE)
    else:
        domains = [arg]
    for d in domains:
        bp = NETWORK / d / "build.py"
        if not bp.exists():
            print(f"SKIP {d}: no build.py")
            continue
        f = parse_build_py(bp)
        ts = emit_config(d, f)
        out_path = ROOT / "src" / "sites" / f"{d}.ts"
        out_path.write_text(ts, encoding="utf-8")
        print(f"OK  {d}: brand='{f.get('SITE_NAME')}' -> {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
