#!/usr/bin/env bash
# Provision a brand-new HVAC site's deploy repo end-to-end:
#   1. Create the private GitHub repo (liamseopro/<domain>)
#   2. Clone it into hvac-network/sites/<domain>/
#   3. Stage the files sync-deploy-repo.sh does NOT produce:
#      CNAME, .nojekyll, .gitignore, robots.txt, llms.txt,
#      assets/js/main.js (per-site brand + email substituted),
#      assets/img/ (default stock photos)
#   4. Enable GitHub Pages + set cname
#   5. First commit + push (the built HTML gets synced in separately by build-site.sh)
#
# Usage:
#   ./scripts/init-deploy-repo.sh <domain> "<brand>" [contact-email]
#   ./scripts/init-deploy-repo.sh exeterheatingcooling.ca "Exeter Heating & Cooling"
#
# Prerequisites:
#   - The site must already be scaffolded + built (src/sites/<domain>.ts exists)
#   - gh CLI authenticated to the liamseopro org
#   - The domain registered + NS delegated to Cloudflare (Headbanger acct)
set -euo pipefail

DOMAIN="${1:?Usage: $0 <domain> \"<brand>\" [contact-email]}"
BRAND="${2:?Usage: $0 <domain> \"<brand>\" [contact-email]}"
EMAIL="${3:-contact@${DOMAIN}}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NETWORK="$ROOT/../hvac-network/sites"
ASTRO_PUBLIC="$ROOT/public"

DEPLOY="$NETWORK/$DOMAIN"

# Sanity: site config must exist (scaffolded first)
if [ ! -f "$ROOT/src/sites/$DOMAIN.ts" ]; then
  echo "FAIL: $ROOT/src/sites/$DOMAIN.ts not found. Run new-site.py first." >&2
  exit 1
fi

# Don't clobber an existing deploy repo
if [ -d "$DEPLOY/.git" ]; then
  echo "SKIP: $DEPLOY already has a .git (repo already provisioned)." >&2
  exit 1
fi

echo "=== [$DOMAIN] Step 1/5: create GitHub repo ==="
if gh repo view "liamseopro/$DOMAIN" >/dev/null 2>&1; then
  echo "  repo already exists on GitHub — cloning existing."
else
  gh repo create "liamseopro/$DOMAIN" --private --confirm 2>/dev/null || \
  gh repo create "liamseopro/$DOMAIN" --private
  echo "  created liamseopro/$DOMAIN (private)"
fi

echo "=== [$DOMAIN] Step 2/5: clone into deploy dir ==="
mkdir -p "$NETWORK"
if [ -d "$DEPLOY" ]; then
  # Dir exists but no .git (maybe a stale artifact dir) — clone into a temp then move
  TMP=$(mktemp -d)
  gh repo clone "liamseopro/$DOMAIN" "$TMP/$DOMAIN" 2>/dev/null || true
  # Move .git into the existing dir
  if [ -d "$TMP/$DOMAIN/.git" ]; then
    mv "$TMP/$DOMAIN/.git" "$DEPLOY/.git"
  else
    # Empty repo, no clone — init fresh
    (cd "$DEPLOY" && git init -q && git remote add origin "https://github.com/liamseopro/$DOMAIN.git")
  fi
  rm -rf "$TMP"
else
  gh repo clone "liamseopro/$DOMAIN" "$DEPLOY" 2>/dev/null || {
    # New empty repo — clone fails, so init locally and add remote
    mkdir -p "$DEPLOY"
    (cd "$DEPLOY" && git init -q && git remote add origin "https://github.com/liamseopro/$DOMAIN.git")
  }
fi
echo "  deploy repo at $DEPLOY"

echo "=== [$DOMAIN] Step 3/5: stage non-synced files ==="

# CNAME (the custom domain for GitHub Pages)
printf '%s' "$DOMAIN" > "$DEPLOY/CNAME"

# .nojekyll (required so GH Pages serves /assets/ without Jekyll processing)
touch "$DEPLOY/.nojekyll"

# .gitignore
cat > "$DEPLOY/.gitignore" <<'EOF'
__pycache__/
*.pyc
.DS_Store
EOF

# robots.txt (allow all crawlers including AI)
cat > "$DEPLOY/robots.txt" <<EOF
User-agent: *
Allow: /
Sitemap: https://$DOMAIN/sitemap-index.xml
EOF

# llms.txt will be generated by the build; placeholder if build hasn't synced yet
[ -f "$DEPLOY/llms.txt" ] || printf '# %s\nHVAC services in Ontario.\n' "$BRAND" > "$DEPLOY/llms.txt"

# assets/js/main.js — per-site (brand in header comment + fallback email)
# Escape & and | in BRAND/EMAIL for safe sed replacement (& = matched pattern in sed).
BRAND_ESC=$(printf '%s' "$BRAND" | sed 's/[&|]/\\&/g')
mkdir -p "$DEPLOY/assets/js"
sed -e "s|Ajax Heating & Cooling|$BRAND_ESC|g" \
    -e "s|contact@londonheatingcooling.ca|$EMAIL|g" \
    "$ASTRO_PUBLIC/assets/js/main.js" > "$DEPLOY/assets/js/main.js"
echo "  staged CNAME, .nojekyll, .gitignore, robots.txt, llms.txt, assets/js/main.js (brand + email substituted)"

# assets/img/ — copy the shared stock pool (logos + hero + og generated separately by ckm:design)
if [ -d "$ASTRO_PUBLIC/assets/img/wp" ]; then
  mkdir -p "$DEPLOY/assets/img/wp"
  cp -R "$ASTRO_PUBLIC/assets/img/wp/." "$DEPLOY/assets/img/wp/" 2>/dev/null || true
  echo "  staged assets/img/wp/ (default stock photos)"
fi
# favicon + og-default (shared defaults; replaced when ckm:design generates branded ones)
for f in favicon.svg apple-touch-icon.png og-default.png badge-quality.png; do
  [ -f "$ASTRO_PUBLIC/assets/img/$f" ] && cp "$ASTRO_PUBLIC/assets/img/$f" "$DEPLOY/assets/img/$f" 2>/dev/null || true
done

echo "=== [$DOMAIN] Step 4/5: enable GitHub Pages + set cname ==="
# Enable Pages on main branch (legacy build type for static)
gh api -X POST "repos/liamseopro/$DOMAIN/pages" \
  -f build_type=legacy -f 'source[branch]=main' 2>/dev/null || \
gh api -X POST "repos/liamseopro/$DOMAIN/pages" \
  -f source='{"branch":"main"}' 2>/dev/null || \
  echo "  (Pages may already be enabled — continuing)"

# Set the cname
gh api -X PUT "repos/liamseopro/$DOMAIN/pages" -f "cname=$DOMAIN" 2>/dev/null || true
echo "  Pages enabled, cname=$DOMAIN"

echo "=== [$DOMAIN] Step 5/5: initial commit + push ==="
(cd "$DEPLOY"
  git add -A
  git commit -q -m "Initial provision: CNAME, assets, config files" 2>/dev/null || echo "  (nothing to commit yet)"
  git push -q origin main 2>/dev/null || git push -q -u origin main 2>/dev/null || echo "  (push will happen after build sync)"
)

echo ""
echo "=== [$DOMAIN] DONE ==="
echo "Next steps:"
echo "  1. Build + sync the HTML:  HVAC_SITE=$DOMAIN ./scripts/build-site.sh"
echo "  2. Commit + push the synced build:  (cd $DEPLOY && git add -A && git commit -m 'Initial build' && git push)"
echo "  3. Create DNS records on Headbanger CF (cloudflare-bulk skill):"
echo "     apex A x4 -> 185.199.108/109/110/111.153 grey; www CNAME -> liamseopro.github.io grey"
echo "  4. Verify HTTPS 200 at https://$DOMAIN (cert provisions after DNS resolves)"
echo "  5. Enable CF email routing for contact@$DOMAIN (-> hvac-email-router Worker)"
